# application:properties for API Gateway
server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes[0]:
        id: say-hello
        uri: lb://user-service
        predicates[0]: Path=/api/user/**
      routes[1]:
        id: change-body
        uri: lb://user-service
        predicates[0]: Path=/api/body/**
    
# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/